ABATE.Washington.Web/Models/Core Partials/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CoreModels = ABATE.Washington.Core.Models;

namespace ABATE.Washington.Web.Models
{
    public partial class Document : CoreModels.Document
    {
        [NotMapped]
        public HttpPostedFileBase File { get; set; }

        
    }
}

ABATE.Washington.Web/Controllers/CitationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using ABATE.Washington.Core.Models;
using ABATE.Washington.Web.Models;
using ABATE.Washington.Web.Services;
using ABATE.Washington.Core.Services;


namespace ABATE.Washington.Web.Controllers
{
    public class CitationsController : Controller
    {
        private readonly IUsersService usersService;
        private readonly INotificationService notificationService;

        public CitationsController(IUsersService usersService, INotificationService notificationService)
        {
            this.usersService = usersService;
            this.notificationService = notificationService;
        }

        public ActionResult News() { return View(); }
        public ActionResult LegalLetters() { return View(); }
        public ActionResult Documents() { return View(); }
        public ActionResult RegisterCitation() { return View(TempData["Citation"] != null ? TempData["Citation"] : new Citation() { IssuedDate = DateTime.Now }); }
        public ActionResult RegistrationSuccessful() { return View(); }
        // GET: Citations
        public ActionResult Index()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [CaptchaMvc.Attributes.CaptchaVerify("Captcha is not valid")]
        public ActionResult SubmitCitation(Citation citation)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var context = ApplicationContext.Create())
                    {
                        context.Citations.Add(citation);
                        context.SaveChanges();

                        var notificationAddresses = usersService.GetUsersInRole(ApplicationRoles.CitationAdmin);
                        var emailList = string.Join(",", notificationAddresses.Data.Select(s => s.Email));
                        var NotificationBody = Extensions.RenderRazorViewToString(this.ControllerContext, "_CitationEmail", citation, this.ViewData, this.TempData);
                        notificationService.SendNotification(emailList, "abate_noreply@abate-wa.org", NotificationBody, "Citation Report Received");

                        return RedirectToAction("RegistrationSuccessful");
                    }
                }
                else { TempData["ErrorMessage"] = "Captcha was incorrect, please try again"; TempData["Citation"] = citation;  return Redirect("RegisterCitation"); }
            }
            catch
            {
                throw;
            }

        }


    }
}

ABATE.Washington.Web/Controllers/DocumentsController.cs
using ABATE.Washington.Web.Models;
using MuPDFLib;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Http;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using ABATE.Washington.Core.Models;

namespace ABATE.Washington.Web.Controllers
{
    public class DocumentsController : Controller
    {
        private ApplicationContext context;

        public DocumentsController(ApplicationContext _context)
        {
            this.context = _context;
        }

        [HttpPost]
        public JsonResult Post()
        {
            List<string> DocumentPaths = new List<string>();

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }

                if (file.ContentType == "application/pdf")
                {
                    MuPDFLib.MuPDF pdfFile = new MuPDFLib.MuPDF(fileData, null);
                    pdfFile.Page = 1;

                    System.Drawing.Bitmap image = pdfFile.GetBitmap(0, 0, 150, 150, 0, RenderType.RGB, true, false, 0);
                    image.Save(Server.MapPath("/Content/files/") + file.FileName + ".png", ImageFormat.Png);

                    Models.Document imageFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/" + Uri.EscapeDataString(file.FileName + ".png"),
                        Title = file.FileName,
                        MimeType = "image/png"
                    };
                    using (var context = new ApplicationContext())
                    {
                        context.Documents.Add(imageFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        DocumentPaths.Add(imageFile.DocumentPath);
                    }
                }
                else
                {
                    System.IO.File.WriteAllBytes((Server.MapPath("/Content/files/") + file.FileName), fileData);

                    Models.Document saveFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/" + Uri.EscapeDataString(file.FileName),
                        //FileContents = fileData,
                        Title = file.FileName,
                        MimeType = file.ContentType
                    };
                    using (var context = new ApplicationContext())
                    {
                        context.Documents.Add(saveFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        DocumentPaths.Add(saveFile.DocumentPath);
                    }
                }
            }
            return Json(DocumentPaths);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> PostFile(Models.Document document)
        {
            List<string> DocumentPaths = new List<string>();

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }

                Guid fileGuid = Guid.NewGuid();

                System.IO.File.WriteAllBytes((Server.MapPath("/Content/files/") + Uri.EscapeDataString(fileGuid.ToString() + Path.GetExtension(file.FileName))), fileData);

                Models.Document saveFile = new Models.Document
                {
                    DocumentPath = "/Content/files/" + Uri.EscapeDataString(fileGuid.ToString() + Path.GetExtension(file.FileName)),
                    PageUrl = document.PageUrl,
                    Category = document.Category,
                    //FileContents = fileData,
                    Title = file.FileName,
                    MimeType = file.ContentType
                };
                using (var context = new ApplicationContext())
                {
                    try
                    {
                       

                        context.Documents.Add(saveFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        DocumentPaths.Add(saveFile.DocumentPath);
                    }
                    catch(Exception ex)
                    {

                    }
                }

            }
            return new HttpResponseMessage();
        }

        [HttpGet]
        public async Task<JsonResult> Get()
        {

            JavaScriptSerializer serializer = new JavaScriptSerializer();

            var query = context.Documents.Where(s => s.PageUrl == Request.UrlReferrer.PathAndQuery);
            var grouped = query.GroupBy(grp => grp.Category);
            var result = grouped.Select(grp => new { Category = grp.Key, Documents = grp.ToList() });

            return Json(result, JsonRequestBehavior.AllowGet);


        }

        //[HttpGet]
        //public FileResult Get(int fileId)
        //{
        //    return new FileContentResult(new byte[] { }, "");
        //}

        [HttpDelete]
        public JsonResult Delete()
        {
            return Json("");
        }

        [HttpPut]
        public JsonResult Put()
        {
            return Json("");
        }
    }
}

ABATE.Washington.Web/Controllers/NewsController.cs
using ABATE.Washington.Web.Models;
using MuPDFLib;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ABATE.Washington.Core.Models;


namespace ABATE.Washington.Web.Controllers
{
    public class NewsController : Controller
    {
        private readonly ApplicationContext context;

        public NewsController(ApplicationContext context)
        {
            this.context = context;
        }

        public ActionResult News() { return View(); }

        public ActionResult MRFNews() { return View(); }
        public ActionResult FlyersForms() { return View(); }

        public ActionResult FreedomNewsletter()
        {
            NewsletterViewModel model = new NewsletterViewModel();


            using(var context = new ApplicationContext())
            {
                
                ViewBag.Volumes = context.NewsletterVolumes.OrderByDescending(v => v.VolumeNumber).ToList().Select(v => new SelectListItem { Text = String.Format("Volume {0}: {1}", v.VolumeNumber, v.VolumeDate.Year), Value = v.id.ToString() }).ToList();
                //model.NewsletterVolumes = context.NewsletterVolumes.Include("Issues").Include("Issues.Cover").Include("Issues.File").Where(v => v.Issues.Any()).Select(s => s).OrderByDescending(n => n.VolumeNumber).ToList();
                var newsletters = context.Newsletters.Include("Cover").Include("File").ToList();

                model.NewsletterVolumes =  newsletters
                    .GroupBy(grp => grp.Volume)
                    .OrderByDescending(grp => grp.Key.VolumeNumber)
                    .Select(grp => new NewsletterVolumeView{ 
                        id = grp.Key.id, 
                        VolumeNumber = grp.Key.VolumeNumber, 
                        VolumeDate = grp.Key.VolumeDate, 
                        Issues = grp.OrderBy(i => i.IssueDate).ToList() 
                    }).ToList();
                
                
            }
            
            

           
            return View(model);
        }

        [HttpGet]
        [Route("News/{Volume}/{Issue}")]
        public FileContentResult GetIssue(int Volume, int Issue)
        {
            var newsletter = context.Newsletters.SingleOrDefault(s => s.Volume.VolumeNumber == Volume && s.IssueDate.Month == Issue);

            if (newsletter == null)
                throw new FileNotFoundException();

            var fileContent = newsletter.File.FileContents;



            throw new NotImplementedException();

        }

        [HttpPost]
        public ActionResult AddNewsletter(Newsletter newsletter)
        {
            using(var context = new ApplicationContext()){
                NewsletterVolume volume = context.NewsletterVolumes.Where(v => v.id == newsletter.VolumeId).FirstOrDefault();
                newsletter.IssueDate = new DateTime(volume.VolumeDate.Year, newsletter.IssueDate.Month, 1);
                volume.Issues.Add(newsletter);
                context.SaveChanges();
            }

            return Json("");
        }

        [HttpPost]
        public JsonResult Post()
        {
            List<string> DocumentPaths = new List<string>();

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }

                Guid fileGuid = Guid.NewGuid();

                if (file.ContentType == "application/pdf")
                {
                    MuPDFLib.MuPDF pdfFile = new MuPDFLib.MuPDF(fileData, null);
                    pdfFile.Page = 1;
                    System.Drawing.Bitmap image = pdfFile.GetBitmap(0, 0, 72, 72, 0, RenderType.RGB, true, false, 0);
                    image.Save(Server.MapPath("/Content/files/News/StateNewsletters/") + fileGuid + ".png", ImageFormat.Png);

                    Models.Document coverFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/News/StateNewsletters/" + Uri.EscapeDataString(fileGuid.ToString() + ".png"),
                        Title = file.FileName,
                        MimeType = "image/png"
                    };


                    System.IO.File.WriteAllBytes((Server.MapPath("/Content/files/News/StateNewsletters/") + fileGuid.ToString() + Path.GetExtension(file.FileName)), fileData);

                    Models.Document documentFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/News/StateNewsletters/" + Uri.EscapeDataString(fileGuid.ToString() + Path.GetExtension(file.FileName)),
                        //FileContents = fileData,
                        Title = file.FileName,
                        MimeType = file.ContentType
                    };


                    using (var context = new ApplicationContext())
                    {
                        context.Documents.Add(coverFile.Retract().To<Core.Models.Document>());
                        context.Documents.Add(documentFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        
                        
                    }
                    return Json(new
                    {
                        CoverId = coverFile.Id,
                        CoverPath = coverFile.DocumentPath,
                        FileId = documentFile.Id,
                        FilePath = documentFile.DocumentPath
                    });
                }

                
            }
            return Json("");
        }



        // GET: News
        public ActionResult Index()
        {
            return View();
        }
    }
}

ABATE.Washington.Web/Views/Citations/Documents.cshtml
@{
    ViewBag.Title = "Documents";
}

<h2>Citations Documents</h2>

@Html.Partial("_Documents")

ABATE.Washington.Web/Views/Citations/LegalLetters.cshtml
@{
    ViewBag.Title = "LegalLetters";
}

<h2>Legal Letters</h2>

@Html.Partial("_Documents")

ABATE.Washington.Web/Views/Citations/News.cshtml
@{
    ViewBag.Title = "News";
}

<h2>News</h2>

ABATE.Washington.Web/Views/Citations/RegisterCitation.cshtml
@model ABATE.Washington.Core.Models.Citation
@{
    ViewBag.Title = "RegisterCitation";

}


<h2 class="text-center">Citation Form</h2>
<div class="row">
    <div class="col-md-12">
        ABATE of Washington is gathering information regarding citations issued for "Illegal helmets", "profiling", proceeding through a malfunctioning red-light traffic signal, and other motorcyclist issues. We have decided to begin collecting facts regarding the issuance of these citations.  In order to make a change, we need hard facts.  With respect for your privacy, we need a detailed description of your citation,  to allow to better fight for your rights in Olympia.  In order to compile data correctly, we are asking for the following:
    </div>
</div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">

        @using (Html.BeginForm("SubmitCitation", "Citations", "POST"))
        {
            @Html.AntiForgeryToken()
            <fieldset>
                <legend></legend>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.CitationNumber, "Citation Number")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextBoxFor(model => model.CitationNumber, new { @placeholder = "Citation Number" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.CodeCited, "Code Cited")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextBoxFor(model => model.CodeCited, new { @placeholder = "Legal Code Cited" })
                        @Html.RadioButtonFor(model => model.LegalCode, "RCW")
                        @Html.LabelFor(model => model.LegalCode, "RCW")
                        @Html.RadioButtonFor(model => model.LegalCode, "WAC")
                        @Html.LabelFor(model => model.LegalCode, "WAC")
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.IssuedDate, "Issued Date")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextBoxFor(model => model.IssuedDate, "{0:MM/dd/yyyy}", new { @class = "datepicker", @value = DateTime.Now.ToShortDateString() })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.City, "Location")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextBoxFor(model => model.City, new { @placeholder = "City" }), @Html.TextBoxFor(model => model.County, new { @placeholder = "County" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.OfficerName, "Officer's Full Name")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextBoxFor(model => model.OfficerName, new { @style = "width: 300px;" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.OfficerBadgeNumber, "Officer's Badge Number")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextBoxFor(model => model.OfficerBadgeNumber, new { @style = "width: 300px;" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.ContactFirstName, "Your Name (Optional)")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">

                        @Html.TextBoxFor(model => model.ContactFirstName, new { @placeholder = "First" })
                        @Html.TextBoxFor(model => model.ContactLastName, new { @placeholder = "Last" })

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.ContactPhone, "Your Phone Number (Optional)")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextBoxFor(model => model.ContactPhone)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.ContactEmail, "Your Email")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextBoxFor(model => model.ContactEmail, new { @style = "width: 300px;" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.InitialDetails, "Details regarding the initial stop (e.g. Probable cause, etc.)")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextAreaFor(model => model.InitialDetails, new { @style = "width: 300px; height: 100px;" })
                        <br />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <span class="text-danger">@TempData["ErrorMessage"]</span>
                        <button class="g-recaptcha"
                                data-sitekey="6LfvXXYUAAAAAEuEQZEFo6yytKqQ9PFDt223W3IY"
                                data-callback="YourOnSubmitFn">
                            Submit
                        </button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <input type="submit" value="Submit" class="btn" />
                        <input type="reset" value="Reset" class="btn" />
                    </div>
                </div>

            </fieldset>



        }
        <br />
        <br />
        <p class="text-center">Privacy Statement<br />
        We consider your personal information PRIVATE ... and it will remain so.</p>
    </div>
    <div class="col-md-2"></div>
</div>

<script src='https://www.google.com/recaptcha/api.js'></script>
<script>
    $(document).ready(function () {
        $('.datepicker').datepicker();
    });

</script>

ABATE.Washington.Web/Views/Citations/RegistrationSuccessful.cshtml
@{
    ViewBag.Title = "Citation Registered";
}

<h2>Citation Registered Successfully</h2>

<p>Citation was registered successfully.  Thank you for your input.</p>

ABATE.Washington.Web/Views/Citations/_CitationEmail.cshtml
@model ABATE.Washington.Core.Models.Citation

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
            
            <fieldset>
                <legend></legend>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.CitationNumber, "Citation Number")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.DisplayFor(model => model.CitationNumber, new { @placeholder = "Citation Number" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.CodeCited, "Code Cited")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.DisplayFor(model => model.CodeCited, new { @placeholder = "Legal Code Cited" })
                        @Html.LabelFor(model => model.LegalCode, "Legal Code")
                        @Html.DisplayFor(model => model.LegalCode)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.IssuedDate, "Issued Date")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.DisplayFor(model => model.IssuedDate, "{0:MM/dd/yyyy}", new { @class = "datepicker", @value = DateTime.Now.ToShortDateString() })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.City, "Location")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.DisplayFor(model => model.City, new { @placeholder = "City" }), @Html.DisplayFor(model => model.County, new { @placeholder = "County" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.OfficerName, "Officer's Full Name")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.DisplayFor(model => model.OfficerName, new { @style = "width: 300px;" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.OfficerBadgeNumber, "Officer's Badge Number")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.DisplayFor(model => model.OfficerBadgeNumber, new { @style = "width: 300px;" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.ContactFirstName, "Your Name (Optional)")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.DisplayFor(model => model.ContactFirstName, new { @placeholder = "First" })
                        @Html.DisplayFor(model => model.ContactLastName, new { @placeholder = "Last" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.ContactPhone, "Your Phone Number (Optional)")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.DisplayFor(model => model.ContactPhone)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.ContactEmail, "Your Email")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.DisplayFor(model => model.ContactEmail, new { @style = "width: 300px;" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3" style="padding: 10px;">
                        @Html.LabelFor(model => model.InitialDetails, "Details regarding the initial stop (e.g. Probable cause, etc.)")
                    </div>
                    <div class="col-md-9" style="padding: 10px;">
                        @Html.TextAreaFor(model => model.InitialDetails, new { @style = "width: 300px; height: 100px;" })
                        <br />
                    </div>
                </div>
            
            </fieldset>



        
        
    </div>
    <div class="col-md-2"></div>
</div>