ABATE.Washington.Web/Models/Core Partials/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CoreModels = ABATE.Washington.Core.Models;

namespace ABATE.Washington.Web.Models
{
    public partial class Document : CoreModels.Document
    {
        [NotMapped]
        public HttpPostedFileBase File { get; set; }

        
    }
}

ABATE.Washington.Web/Controllers/DocumentsController.cs
using ABATE.Washington.Web.Models;
using MuPDFLib;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Http;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using ABATE.Washington.Core.Models;

namespace ABATE.Washington.Web.Controllers
{
    public class DocumentsController : Controller
    {
        private ApplicationContext context;

        public DocumentsController(ApplicationContext _context)
        {
            this.context = _context;
        }

        [HttpPost]
        public JsonResult Post()
        {
            List<string> DocumentPaths = new List<string>();

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }

                if (file.ContentType == "application/pdf")
                {
                    MuPDFLib.MuPDF pdfFile = new MuPDFLib.MuPDF(fileData, null);
                    pdfFile.Page = 1;

                    System.Drawing.Bitmap image = pdfFile.GetBitmap(0, 0, 150, 150, 0, RenderType.RGB, true, false, 0);
                    image.Save(Server.MapPath("/Content/files/") + file.FileName + ".png", ImageFormat.Png);

                    Models.Document imageFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/" + Uri.EscapeDataString(file.FileName + ".png"),
                        Title = file.FileName,
                        MimeType = "image/png"
                    };
                    using (var context = new ApplicationContext())
                    {
                        context.Documents.Add(imageFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        DocumentPaths.Add(imageFile.DocumentPath);
                    }
                }
                else
                {
                    System.IO.File.WriteAllBytes((Server.MapPath("/Content/files/") + file.FileName), fileData);

                    Models.Document saveFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/" + Uri.EscapeDataString(file.FileName),
                        //FileContents = fileData,
                        Title = file.FileName,
                        MimeType = file.ContentType
                    };
                    using (var context = new ApplicationContext())
                    {
                        context.Documents.Add(saveFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        DocumentPaths.Add(saveFile.DocumentPath);
                    }
                }
            }
            return Json(DocumentPaths);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> PostFile(Models.Document document)
        {
            List<string> DocumentPaths = new List<string>();

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }

                Guid fileGuid = Guid.NewGuid();

                System.IO.File.WriteAllBytes((Server.MapPath("/Content/files/") + Uri.EscapeDataString(fileGuid.ToString() + Path.GetExtension(file.FileName))), fileData);

                Models.Document saveFile = new Models.Document
                {
                    DocumentPath = "/Content/files/" + Uri.EscapeDataString(fileGuid.ToString() + Path.GetExtension(file.FileName)),
                    PageUrl = document.PageUrl,
                    Category = document.Category,
                    //FileContents = fileData,
                    Title = file.FileName,
                    MimeType = file.ContentType
                };
                using (var context = new ApplicationContext())
                {
                    try
                    {
                       

                        context.Documents.Add(saveFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        DocumentPaths.Add(saveFile.DocumentPath);
                    }
                    catch(Exception ex)
                    {

                    }
                }

            }
            return new HttpResponseMessage();
        }

        [HttpGet]
        public async Task<JsonResult> Get()
        {

            JavaScriptSerializer serializer = new JavaScriptSerializer();

            var query = context.Documents.Where(s => s.PageUrl == Request.UrlReferrer.PathAndQuery);
            var grouped = query.GroupBy(grp => grp.Category);
            var result = grouped.Select(grp => new { Category = grp.Key, Documents = grp.ToList() });

            return Json(result, JsonRequestBehavior.AllowGet);


        }

        //[HttpGet]
        //public FileResult Get(int fileId)
        //{
        //    return new FileContentResult(new byte[] { }, "");
        //}

        [HttpDelete]
        public JsonResult Delete()
        {
            return Json("");
        }

        [HttpPut]
        public JsonResult Put()
        {
            return Json("");
        }
    }
}

ABATE.Washington.Web/Controllers/LegislativeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABATE.Washington.Web.Controllers
{
    public class LegislativeController : Controller
    {

        public ActionResult News() { return View(); }
        public ActionResult CurrentBills() { return View(); }
        public ActionResult Representatives() { return View(); }
        public ActionResult HowToContact() { return View(); }
        public ActionResult StateLegislators() { return View(); }
        public ActionResult StateCongressmen() { return View(); }
        public ActionResult USRepresentatives() { return View(); }
        public ActionResult LegislativeEvents() { return View(); }
        public ActionResult BlackThursday() { return View(); }
        public ActionResult FreedomRally() { return View(); }
        public ActionResult Documents() { return View(); }
        public ActionResult USDefenders() { return View(); }
        public ActionResult DefendersNews() { return View(); }
        public ActionResult CTAs() { return View(); }
        public ActionResult FromYourLAO() { return View(); }

        // GET: Legislative
        public ActionResult Index()
        {
            return View();
        }
    }
}

ABATE.Washington.Web/Controllers/NewsController.cs
using ABATE.Washington.Web.Models;
using MuPDFLib;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ABATE.Washington.Core.Models;


namespace ABATE.Washington.Web.Controllers
{
    public class NewsController : Controller
    {
        private readonly ApplicationContext context;

        public NewsController(ApplicationContext context)
        {
            this.context = context;
        }

        public ActionResult News() { return View(); }

        public ActionResult MRFNews() { return View(); }
        public ActionResult FlyersForms() { return View(); }

        public ActionResult FreedomNewsletter()
        {
            NewsletterViewModel model = new NewsletterViewModel();


            using(var context = new ApplicationContext())
            {
                
                ViewBag.Volumes = context.NewsletterVolumes.OrderByDescending(v => v.VolumeNumber).ToList().Select(v => new SelectListItem { Text = String.Format("Volume {0}: {1}", v.VolumeNumber, v.VolumeDate.Year), Value = v.id.ToString() }).ToList();
                //model.NewsletterVolumes = context.NewsletterVolumes.Include("Issues").Include("Issues.Cover").Include("Issues.File").Where(v => v.Issues.Any()).Select(s => s).OrderByDescending(n => n.VolumeNumber).ToList();
                var newsletters = context.Newsletters.Include("Cover").Include("File").ToList();

                model.NewsletterVolumes =  newsletters
                    .GroupBy(grp => grp.Volume)
                    .OrderByDescending(grp => grp.Key.VolumeNumber)
                    .Select(grp => new NewsletterVolumeView{ 
                        id = grp.Key.id, 
                        VolumeNumber = grp.Key.VolumeNumber, 
                        VolumeDate = grp.Key.VolumeDate, 
                        Issues = grp.OrderBy(i => i.IssueDate).ToList() 
                    }).ToList();
                
                
            }
            
            

           
            return View(model);
        }

        [HttpGet]
        [Route("News/{Volume}/{Issue}")]
        public FileContentResult GetIssue(int Volume, int Issue)
        {
            var newsletter = context.Newsletters.SingleOrDefault(s => s.Volume.VolumeNumber == Volume && s.IssueDate.Month == Issue);

            if (newsletter == null)
                throw new FileNotFoundException();

            var fileContent = newsletter.File.FileContents;



            throw new NotImplementedException();

        }

        [HttpPost]
        public ActionResult AddNewsletter(Newsletter newsletter)
        {
            using(var context = new ApplicationContext()){
                NewsletterVolume volume = context.NewsletterVolumes.Where(v => v.id == newsletter.VolumeId).FirstOrDefault();
                newsletter.IssueDate = new DateTime(volume.VolumeDate.Year, newsletter.IssueDate.Month, 1);
                volume.Issues.Add(newsletter);
                context.SaveChanges();
            }

            return Json("");
        }

        [HttpPost]
        public JsonResult Post()
        {
            List<string> DocumentPaths = new List<string>();

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }

                Guid fileGuid = Guid.NewGuid();

                if (file.ContentType == "application/pdf")
                {
                    MuPDFLib.MuPDF pdfFile = new MuPDFLib.MuPDF(fileData, null);
                    pdfFile.Page = 1;
                    System.Drawing.Bitmap image = pdfFile.GetBitmap(0, 0, 72, 72, 0, RenderType.RGB, true, false, 0);
                    image.Save(Server.MapPath("/Content/files/News/StateNewsletters/") + fileGuid + ".png", ImageFormat.Png);

                    Models.Document coverFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/News/StateNewsletters/" + Uri.EscapeDataString(fileGuid.ToString() + ".png"),
                        Title = file.FileName,
                        MimeType = "image/png"
                    };


                    System.IO.File.WriteAllBytes((Server.MapPath("/Content/files/News/StateNewsletters/") + fileGuid.ToString() + Path.GetExtension(file.FileName)), fileData);

                    Models.Document documentFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/News/StateNewsletters/" + Uri.EscapeDataString(fileGuid.ToString() + Path.GetExtension(file.FileName)),
                        //FileContents = fileData,
                        Title = file.FileName,
                        MimeType = file.ContentType
                    };


                    using (var context = new ApplicationContext())
                    {
                        context.Documents.Add(coverFile.Retract().To<Core.Models.Document>());
                        context.Documents.Add(documentFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        
                        
                    }
                    return Json(new
                    {
                        CoverId = coverFile.Id,
                        CoverPath = coverFile.DocumentPath,
                        FileId = documentFile.Id,
                        FilePath = documentFile.DocumentPath
                    });
                }

                
            }
            return Json("");
        }



        // GET: News
        public ActionResult Index()
        {
            return View();
        }
    }
}

ABATE.Washington.Web/Views/Legislative/BlackThursday.cshtml
<!DOCTYPE html>
@{
    ViewBag.Title = "BlackThursday";
}


<div class="row">
    <div class="col-md-6">
        
        <p>Black Thursday is front and center this month and hopefully everyone has planned their schedules to accommodate being at the Capitol on January 16th!  A review session is planned for January 15th, 6:00pm (until the last person leaves) to take place at the Red Lion Inn (Governor's). A lot of prep work leading up to Black Thursday is going on including supporting Legislators in their own districts (such as participating in Veteran Cemetery Honor ceremonies), conversing with Legislative Assistants (LAs) and reviewing our bill presentation strategies.</p>

        <p>Appointments are still coming in so the final appointment schedule can't be known for sure at this time but it is our goal to meet with every Legislator (all 147 of them) and the more people who attend Black Thursday, the easier it is to accomplish this goal.  Hopefully everyone has contacted all 3 of their Legislators and have scheduled an appointment for that day.</p>

        <p><strong>REMEMBER: once you have scheduled an appointment, you need to send that appointment time to the state LAO.  Please send your appointment information via EMAIL and not facebook, text or other medium. Email is:  <a href="mailto:legislative1@abate-wa.org">legislative1@abate-wa.org</a>.</strong></p>

        <p>One of the most common reasons members give on why they don't attend Black Thursday is that they feel uneasy or too uneducated about how to present ABATE's issues to Legislators  but, there are a few things to keep in mind here:  1) Legislators are just people too and they don't expect their constituents to be well versed in legislative language and, 2) presentation materials will be provided for anyone who meets with a Legislator and, 3) a review session will be held on Wednesday evening to help prepare members on how to present our issues.</p>

        <p>Remember, there are many ways to help make Black Thursday a success - not just discussing our bills with Legislators. Since it is always better to have more than one person attend an appointment, you could simply sit in on a meeting and see how we handle them or, you could help keep things organized in the staging area (Columbia Room) or, you could join the motorcycle ride-in and show up at the Capitol steps for speakers and photos (it helps to have as many motorcyclists as possible participate in this, even if you don't stay for the rest of the event).  If you have never been to Black Thursday because you feel you can't speak with Legislators, then please consider helping out in other ways.  Those who have attended Black Thursday events have always given positive feedback about their experience.</p>

        <br />

        <p>
            <h4>Black Thursday Agenda</h4>
            <em>See our @Html.ActionLink("Current Bills", "CurrentBills", "Legislative") to see bill sponsors and talking points for Black Thursday.</em>
            <br />
            <br />
            7:30 am Columbia Room Open<br />
            8:00am - 5:00pm - Appointments<br />
            10:00am KSU from Hawk's Prairie Casino<br />
            10:00am - 10:30am - Ride In to Capitol<br />
            10:45am - 11:30am - Speakers on the Steps<br />
            11:30am - Group Photo on the Steps<br />
            5:30pm - ?? Meet & Greet at Red Lion Governor's<br />
        </p>

        
        <p>When you get a chance, review the Legislative sections from the November and December issues of Freedom magazine to help prepare for our Black Thursday event this month.  Make plans to show up on January 16th and help make it a very successful day for us!</p>

        <p>Louise Bentley</p>
        <p>Brian Lange</p>
    </div>

    <div class="col-md-6">
        
        <div style="text-align: center;"><a href="https://www.abate-wa.org/Content/files/Black%20Thursday%20Flier%202020%20copy%203.jpg" target="_blank"><img src="https://www.abate-wa.org/Content/files/Black%20Thursday%20Flier%202020%20copy%203.jpg" alt="Black Thursday" /></a></div>
        <div>
            <br /><br />Please visit our <a href="https://www.abate-wa.org/Legislative/Documents">Documents and Forms</a> to find more information about our legislative packet other beneficial information regarding our legislative efforts. Or download the <a href="/Content/files/5653a34c-2531-40f6-8358-b7cf21befcc3.pdf" target="_blank" download="BlackThursday2019.pdf">Black Thursday Packet</a> here.
        </div>
    </div>
</div>

ABATE.Washington.Web/Views/Legislative/CurrentBills.cshtml
@{
    ViewBag.Title = "CurrentBills";
}

<h2>Current Bills 2019-2020</h2>
<br />
<br />
<p><h3>Helmet (Safety Gear) Choice </h3>
    <ul>
        <li>allow those who ride to decide what gear is best.</li>
        <li>mandates liability and health insurance (same as auto) for riding without a helmet</li>
        <li>creates a 5 year pilot program study to track head injury statistics</li>
    </ul>

    <h4>HB 1125 - 2019-20</h4>
    Concerning motorcycle helmet use.<br />
    Sponsors: <a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Blake">Blake</a>,
    <a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Griffey">Griffey</a>,
    <a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Walsh">Walsh</a>,
    <a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Young">Young</a>
</p>
<br />
<p>
    <h4>
        SB 5007 - 2019-20
    </h4>
    Concerning motorcycle helmet use.<br />
    Sponsors: <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Rolfes">Rolfes</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Sheldon">Sheldon</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Braun">Braun</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Brown">Brown</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Fortunato">Fortunato</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Kuderer">Kuderer</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Oban">Oban</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Short">Short</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Takko">Takko</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Wagoner">Wagoner</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Warnick">Warnick</a>
</p>
<hr />
<p><h3>Lane Sharing</h3>
    <ul>
        <li>increase motorcycle safety and congestion relief on freeways.</li>
        <li>offer options for motorcycles to negotiate their position on congested freeways.</li>
        <li>reduce chances of rear-end collisions to motorcycles in stopped traffic.</li>
        <li>alleviate rider fatigue and motorcycle overheating for motorcycle riders.</li>
        <li>offer congestion relief by allowing motorcycles to move out of traffic.</li>
    </ul>
    <h4>SB 5254 - 2019-20</h4>
    Modifying the operation of motorcycles on roadways laned for traffic.<br />
    Sponsors: <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Sheldon">Sheldon</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Conway">Conway</a>
</p>
<hr />
<p>
    <h3>Parking</h3>
<p>
    Parking - amend RCW 46.61.575 to allow angle parking for motorcycles
    <ul>
        <li>has passed unanimously but ran out of time in the Senate before session ended.</li>
        <li>angle parking is safer for motorcycles.</li>
        <li>space saver for curbside & parking spaces (allows multiple motorcycles per space). Especially important for cities in need of increasing available curbside space, such as Bellevue.</li>
    </ul>
</p>
<h4>HB 1058 - 2019-20</h4>
    Establishing permissible methods of parking a motorcycle.
<br />
    Sponsors: <a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Irwin">Irwin</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Blake">Blake</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Van Werven">Van Werven</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Bergquist">Bergquist</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Walsh">Walsh</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#MacEwen">MacEwen</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Shea">Shea</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Jinkins">Jinkins</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Wylie">Wylie</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Goodman">Goodman</a>,
<a href="http://leg.wa.gov/house/representatives/pages/default.aspx#Barkis">Barkis</a>
</p>
<br />
<p>
    <h4>SB 5653 - 2019-20</h4>
    Establishing permissible methods of parking a motorcycle.<br />
    Sponsors:
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Fortunato">Fortunato</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Hasegawa">Hasegawa</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Takko">Takko</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Brown">Brown</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Becker">Becker</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Padden">Padden</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Wilson">Wilson, L.</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Schoesler,">Schoesler,</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Short">Short</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Holy">Holy</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Warnick">Warnick</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Sheldon">Sheldon</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Honeyford">Honeyford</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Saldana">Saldana</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Hobbs">Hobbs</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Palumbo">Palumbo</a>,
    <a href="http://leg.wa.gov/senate/senators/pages/default.aspx#Randall">Randall</a>
</p>

ABATE.Washington.Web/Views/Legislative/DefendersNews.cshtml
@{
    ViewBag.Title = "DefendersNews";
}

<h2>DefendersNews</h2>

ABATE.Washington.Web/Views/Legislative/Documents.cshtml
@{
    ViewBag.Title = "Documents";
}

<h2>Legislative Documents</h2>

@Html.Partial("_Documents")

ABATE.Washington.Web/Views/Legislative/FreedomRally.cshtml
@{
    ViewBag.Title = "FreedomRally";
}

<h2>FreedomRally</h2>

ABATE.Washington.Web/Views/Legislative/HowToContact.cshtml
@{
    ViewBag.Title = "HowToContact";
}

<h2 class="text-center">How to Contact Your Legislator</h2>

<div class="row">
    <div class="col-md-12">

        <p>Two ways to contact your State legislators to voice concerns, opposition or support of Bills:</p>

        <p>
            If you follow the following steps on-line, it makes it easy to send an email
            to all 3 of the state legislators from your district in about 5 minutes.
        </p>


        <h4>EMail</h4>
        <ul class="list-style-none">
            <li>1. Go to : @Html.ExternalLink("http://www.leg.wa.gov/legislature", "http://www.leg.wa.gov/legislature", new { target ="_blank" })</li>
            <li>2. Click 'Find your Legislator' on the left hand side</li>
            <li>3. On the tab 'find your district', type in your address information</li>
            <li>4. Click on any of the legislators listed (this will bring you to their web page)</li>
            <li>5. Click the word 'e-mail' (just to the right of their picture)</li>
            <li>6. Type in your address again</li>
            <li>7. Fill in the blanks on this page and be sure to check off the following:</li>
            <li>
                <ul class="list-style-none">
                    <li>a. To receive a a response, please check..........................</li>
                    <li>b. Check here if you wish to send a copy to.........................</li>
                </ul>
                (This will send the same email to your district Senator and both of your representatives, and it will make sure that you receive a response from your legislator.)
            </li>



            <li>8. cut and paste one of the form letters that ABATE provided, or put in wording of your own.</li>
        </ul>

        <h4>Phone</h4>

        <p>Toll free number in Olympia to voice your concerns about a bill:</p>

        <p>1-800-562-6000</p>
    </div>

</div>

ABATE.Washington.Web/Views/Legislative/LegislativeEvents.cshtml
@{
    ViewBag.Title = "LegislativeEvents";
}

<h2>LegislativeEvents</h2>

ABATE.Washington.Web/Views/Legislative/News.cshtml
@{
    ViewBag.Title = "News";
}

<h2>News</h2>

ABATE.Washington.Web/Views/Legislative/Representatives.cshtml
@{
    ViewBag.Title = "Representatives";
}

<h2>Representatives</h2>

ABATE.Washington.Web/Views/Legislative/StateCongressmen.cshtml
@{
    ViewBag.Title = "StateCongressmen";
}

<h2>StateCongressmen</h2>

ABATE.Washington.Web/Views/Legislative/StateLegislators.cshtml
@{
    ViewBag.Title = "StateLegislators";
}

<h2>StateLegislators</h2>

ABATE.Washington.Web/Views/Legislative/USDefenders.cshtml
@{
    ViewBag.Title = "USDefenders";
}

<h2>USDefenders</h2>

ABATE.Washington.Web/Views/Legislative/USRepresentatives.cshtml
@{
    ViewBag.Title = "USRepresentatives";
}

<h2>USRepresentatives</h2>