ABATE.Washington.Web/Models/Core Partials/Document.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CoreModels = ABATE.Washington.Core.Models;

namespace ABATE.Washington.Web.Models
{
    public partial class Document : CoreModels.Document
    {
        [NotMapped]
        public HttpPostedFileBase File { get; set; }

        
    }
}

ABATE.Washington.Web/Controllers/DocumentsController.cs
using ABATE.Washington.Web.Models;
using MuPDFLib;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Http;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using ABATE.Washington.Core.Models;

namespace ABATE.Washington.Web.Controllers
{
    public class DocumentsController : Controller
    {
        private ApplicationContext context;

        public DocumentsController(ApplicationContext _context)
        {
            this.context = _context;
        }

        [HttpPost]
        public JsonResult Post()
        {
            List<string> DocumentPaths = new List<string>();

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }

                if (file.ContentType == "application/pdf")
                {
                    MuPDFLib.MuPDF pdfFile = new MuPDFLib.MuPDF(fileData, null);
                    pdfFile.Page = 1;

                    System.Drawing.Bitmap image = pdfFile.GetBitmap(0, 0, 150, 150, 0, RenderType.RGB, true, false, 0);
                    image.Save(Server.MapPath("/Content/files/") + file.FileName + ".png", ImageFormat.Png);

                    Models.Document imageFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/" + Uri.EscapeDataString(file.FileName + ".png"),
                        Title = file.FileName,
                        MimeType = "image/png"
                    };
                    using (var context = new ApplicationContext())
                    {
                        context.Documents.Add(imageFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        DocumentPaths.Add(imageFile.DocumentPath);
                    }
                }
                else
                {
                    System.IO.File.WriteAllBytes((Server.MapPath("/Content/files/") + file.FileName), fileData);

                    Models.Document saveFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/" + Uri.EscapeDataString(file.FileName),
                        //FileContents = fileData,
                        Title = file.FileName,
                        MimeType = file.ContentType
                    };
                    using (var context = new ApplicationContext())
                    {
                        context.Documents.Add(saveFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        DocumentPaths.Add(saveFile.DocumentPath);
                    }
                }
            }
            return Json(DocumentPaths);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> PostFile(Models.Document document)
        {
            List<string> DocumentPaths = new List<string>();

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }

                Guid fileGuid = Guid.NewGuid();

                System.IO.File.WriteAllBytes((Server.MapPath("/Content/files/") + Uri.EscapeDataString(fileGuid.ToString() + Path.GetExtension(file.FileName))), fileData);

                Models.Document saveFile = new Models.Document
                {
                    DocumentPath = "/Content/files/" + Uri.EscapeDataString(fileGuid.ToString() + Path.GetExtension(file.FileName)),
                    PageUrl = document.PageUrl,
                    Category = document.Category,
                    //FileContents = fileData,
                    Title = file.FileName,
                    MimeType = file.ContentType
                };
                using (var context = new ApplicationContext())
                {
                    try
                    {
                       

                        context.Documents.Add(saveFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        DocumentPaths.Add(saveFile.DocumentPath);
                    }
                    catch(Exception ex)
                    {

                    }
                }

            }
            return new HttpResponseMessage();
        }

        [HttpGet]
        public async Task<JsonResult> Get()
        {

            JavaScriptSerializer serializer = new JavaScriptSerializer();

            var query = context.Documents.Where(s => s.PageUrl == Request.UrlReferrer.PathAndQuery);
            var grouped = query.GroupBy(grp => grp.Category);
            var result = grouped.Select(grp => new { Category = grp.Key, Documents = grp.ToList() });

            return Json(result, JsonRequestBehavior.AllowGet);


        }

        //[HttpGet]
        //public FileResult Get(int fileId)
        //{
        //    return new FileContentResult(new byte[] { }, "");
        //}

        [HttpDelete]
        public JsonResult Delete()
        {
            return Json("");
        }

        [HttpPut]
        public JsonResult Put()
        {
            return Json("");
        }
    }
}

ABATE.Washington.Web/Controllers/NewsController.cs
using ABATE.Washington.Web.Models;
using MuPDFLib;
using System;
using System.Collections.Generic;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ABATE.Washington.Core.Models;


namespace ABATE.Washington.Web.Controllers
{
    public class NewsController : Controller
    {
        private readonly ApplicationContext context;

        public NewsController(ApplicationContext context)
        {
            this.context = context;
        }

        public ActionResult News() { return View(); }

        public ActionResult MRFNews() { return View(); }
        public ActionResult FlyersForms() { return View(); }

        public ActionResult FreedomNewsletter()
        {
            NewsletterViewModel model = new NewsletterViewModel();


            using(var context = new ApplicationContext())
            {
                
                ViewBag.Volumes = context.NewsletterVolumes.OrderByDescending(v => v.VolumeNumber).ToList().Select(v => new SelectListItem { Text = String.Format("Volume {0}: {1}", v.VolumeNumber, v.VolumeDate.Year), Value = v.id.ToString() }).ToList();
                //model.NewsletterVolumes = context.NewsletterVolumes.Include("Issues").Include("Issues.Cover").Include("Issues.File").Where(v => v.Issues.Any()).Select(s => s).OrderByDescending(n => n.VolumeNumber).ToList();
                var newsletters = context.Newsletters.Include("Cover").Include("File").ToList();

                model.NewsletterVolumes =  newsletters
                    .GroupBy(grp => grp.Volume)
                    .OrderByDescending(grp => grp.Key.VolumeNumber)
                    .Select(grp => new NewsletterVolumeView{ 
                        id = grp.Key.id, 
                        VolumeNumber = grp.Key.VolumeNumber, 
                        VolumeDate = grp.Key.VolumeDate, 
                        Issues = grp.OrderBy(i => i.IssueDate).ToList() 
                    }).ToList();
                
                
            }
            
            

           
            return View(model);
        }

        [HttpGet]
        [Route("News/{Volume}/{Issue}")]
        public FileContentResult GetIssue(int Volume, int Issue)
        {
            var newsletter = context.Newsletters.SingleOrDefault(s => s.Volume.VolumeNumber == Volume && s.IssueDate.Month == Issue);

            if (newsletter == null)
                throw new FileNotFoundException();

            var fileContent = newsletter.File.FileContents;



            throw new NotImplementedException();

        }

        [HttpPost]
        public ActionResult AddNewsletter(Newsletter newsletter)
        {
            using(var context = new ApplicationContext()){
                NewsletterVolume volume = context.NewsletterVolumes.Where(v => v.id == newsletter.VolumeId).FirstOrDefault();
                newsletter.IssueDate = new DateTime(volume.VolumeDate.Year, newsletter.IssueDate.Month, 1);
                volume.Issues.Add(newsletter);
                context.SaveChanges();
            }

            return Json("");
        }

        [HttpPost]
        public JsonResult Post()
        {
            List<string> DocumentPaths = new List<string>();

            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];

                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }

                Guid fileGuid = Guid.NewGuid();

                if (file.ContentType == "application/pdf")
                {
                    MuPDFLib.MuPDF pdfFile = new MuPDFLib.MuPDF(fileData, null);
                    pdfFile.Page = 1;
                    System.Drawing.Bitmap image = pdfFile.GetBitmap(0, 0, 72, 72, 0, RenderType.RGB, true, false, 0);
                    image.Save(Server.MapPath("/Content/files/News/StateNewsletters/") + fileGuid + ".png", ImageFormat.Png);

                    Models.Document coverFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/News/StateNewsletters/" + Uri.EscapeDataString(fileGuid.ToString() + ".png"),
                        Title = file.FileName,
                        MimeType = "image/png"
                    };


                    System.IO.File.WriteAllBytes((Server.MapPath("/Content/files/News/StateNewsletters/") + fileGuid.ToString() + Path.GetExtension(file.FileName)), fileData);

                    Models.Document documentFile = new Models.Document
                    {
                        DocumentPath = "/Content/files/News/StateNewsletters/" + Uri.EscapeDataString(fileGuid.ToString() + Path.GetExtension(file.FileName)),
                        //FileContents = fileData,
                        Title = file.FileName,
                        MimeType = file.ContentType
                    };


                    using (var context = new ApplicationContext())
                    {
                        context.Documents.Add(coverFile.Retract().To<Core.Models.Document>());
                        context.Documents.Add(documentFile.Retract().To<Core.Models.Document>());
                        context.SaveChanges();
                        
                        
                    }
                    return Json(new
                    {
                        CoverId = coverFile.Id,
                        CoverPath = coverFile.DocumentPath,
                        FileId = documentFile.Id,
                        FilePath = documentFile.DocumentPath
                    });
                }

                
            }
            return Json("");
        }



        // GET: News
        public ActionResult Index()
        {
            return View();
        }
    }
}

ABATE.Washington.Web/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABATE.Washington.Web.Controllers
{
    public class PagesController : Controller
    {
        // GET: Pages
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Pages/About
        public ActionResult About()
        {
            ViewBag.Title = "About ABATE";
            return View();
        }

        // 
        // GET:  /Home/Pages/{navId}
        public ActionResult Page(string id)
        {
            ViewBag.Title = id;


            return View();
        }
    }
}

ABATE.Washington.Web/Views/Shared/_AddDocument.cshtml
@model ABATE.Washington.Web.Models.Document


@using (Ajax.BeginForm("PostFile", "Documents", FormMethod.Post, new AjaxOptions { }, new { @id = "formFileUpload", @enctype = "multipart/form-data", @class = "attachmentUpload" }))
{
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6">
                    @Html.LabelFor(d => d.Title)
                </div>
                <div class="col-md-6">
                    @Html.TextBoxFor(d => d.Title)
                </div>
                <br />
                <div class="col-md-6">
                    @Html.LabelFor(d => d.Description)
                </div>
                <div class="col-md-6">
                    @Html.TextBoxFor(d => d.Description)
                </div><br />
                <div class="col-md-6">
                    @Html.LabelFor(d => d.Category)
                </div>
                <div class="col-md-6">
                    @Html.TextBoxFor(d => d.Category)
                </div>
            </div>

        </div>
        <div class="col-md-6">
            @Html.HiddenFor(d => d.PageUrl, new { @Value = Request.Url.PathAndQuery })
            <div class="fileupload-buttonbar">
                <label>
                    <span class="btn btn-primary">Add a file...</span>
                    @Html.TextBoxFor(d => d.File, new { @id = "fileUpload_input", @style = "visibility: hidden", @type = "file", @name = "files" })
                    @Html.ValidationMessageFor(d => d.File)
                </label>
                <div class="fileupload-progressbar"></div>
            </div>

        </div>
    </div>


}

<div class="fileupload-content">
    <table class="files"></table>
</div>


<script>
    function saveChanges() {
        if ($('#fileUpload_input').val() == "") {
            return;
        }
        // your ajax submit

        $.ajax({
            url: '@Url.Action("PostFile","Documents")',
            type: 'POST',
            data: new FormData($('.attachmentUpload')[0]),
            processData: false,
            contentType: false,
            success: function (data) {
                $('#addDocumentModal').modal('hide');
            }
        });
    }
</script>

ABATE.Washington.Web/Views/Shared/_Documents.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole(ABATE.Washington.Web.Models.ApplicationRoles.SysAdmin)) {
<div class="row">
    <div class="col-md-pull-3">
        <input type="button" class="btn btn-primary" onclick="$('#addDocumentModal').modal('show');" value="Add file" />
    </div>
</div>
}

<br />
<div class="panel-group" id="accordian" data-bind="visible: loadList">
    <div class="panel panel-default" data-bind="foreach: documents">
        
            <div class="panel-heading">
                <h4><a data-toggle="collapse" data-parent="#accordian" data-bind="attr: { href: '#' + $index() }, text: Category"></a></h4>
            </div>
            <div class="panel-collapse collapse" data-bind="attr: { id: $index }">
                <div class="panel-body">
                    <div class="row" data-bind="foreach: Documents">
                        
                            <div class="col-sm-12"><a data-bind="attr: {href: DocumentPath, download: Title }, text: Title"></a><br />@*<input type="text" data-bind="test: Title, textInput: Title" />*@</div>
                       
                            @*<div class="col-md-4"><h5>Address</h5><br />@issue.Address1<br />@(!string.IsNullOrEmpty(chapter.Address2) ? chapter.Address2 : "") @chapter.City, @chapter.State @chapter.ZipCode<br />@chapter.Phone<br /> @if (chapter.WebSite != null) { Html.ExternalLink(chapter.WebSite, "Chapter Website", new { @target = "_blank" }); }</div>
                            <div class="col-md-4"><h5>Meeting Location: @chapter.MeetingLocation</h5><br />@chapter.MeetingAddress1<br />@(!string.IsNullOrEmpty(chapter.MeetingAddress2) ? @chapter.MeetingAddress2 : "")@chapter.MeetingCity, @chapter.MeetingState @chapter.MeetingZipCode<br />@chapter.MeetingPhone<br /><br /><i>@chapter.MeetingSchedule1<br />@chapter.MeetingSchedule2</i></div>
                            <div class="col-md-4"><embed width="300" height="225" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCAS1DfItlS3Nt7NyOCPakekErNKNigzz4&q=@(HttpUtility.UrlEncode(chapter.MeetingLocationQuery))"></embed></div>*@
                       
                    </div>
                </div>
            </div>
        

    </div>
</div>

<div class="modal fade" id="addDocumentModal" tabindex="-1" role="dialog" aria-labelledby="addDocumentModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title" id="myModalLabel">Add File...</h4>
            </div>
            <div class="modal-body">

                @Html.Partial("_AddDocument", new ABATE.Washington.Web.Models.Document())

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="saveChanges();">Save changes</button>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/ko")




}

<script>
    $(function () {
        var webroot = '@Url.Content("~")';
        

        function DocumentViewListModel() {
            var self = this;

            self.documents = ko.observableArray();

            self.loadList = function () {
                $.getJSON('@Url.Action("Get","Documents")', function (data) {
                    var test = JSON.stringify(data);
                    ko.mapping.fromJS(data, {}, self.documents);
                });
            };

            self.putList = function () {
                var datapackage = ko.mapping.toJSON(self.objects);
                $.ajax({
                    url: webroot + 'api/Products',
                    dataType: 'json',
                    contentType: 'application/json',
                    data: datapackage,
                    type: 'POST',
                    success: function (data) {
                        alert(data);
                    },
                    error: function () {
                        alert('Wha, Wha....');
                    }
                });
            };

            return self;
        }


        var vm = new DocumentViewListModel();
        vm.loadList();
        ko.applyBindings(vm);

    });
</script>

ABATE.Washington.Web/Views/Shared/_Layout.cshtml
@using ABATE.Washington.Core.Models;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='//fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/css/htmlArea")
    @Styles.Render("~/bundles/css/css")
    @Styles.Render("~/bundles/css/fullcalendar")
    @*@Styles.Render("~/bundles/css/Bootstrap")*@
    <link href="/Content/fullcalendar.print.css" rel="stylesheet" media="print">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/fullcalendar")
    @Scripts.Render("~/bundles/ko")



    @Scripts.Render("~/bundles/jHtmlArea")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</head>
<script>
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-72397914-1', 'auto');
    ga('send', 'pageview');

</script>
<script>
    $(document).ready(function () {
        $.ajaxSetup({ cache: false });
    });



</script>
<body>



    <div class="site-header">
        @Html.Partial("_Header")
    </div>
    <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ABATE of Washington", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Home", "Index", "Home")
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("About ABATE", "About", "Pages")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        @Html.ActionLink("About", "About", "Home", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("About ABATE", "About", "Home")</li>
                            <li>@Html.ActionLink("Our History", "History", "Home")</li>
                            <li>@Html.ActionLink("Join ABATE", "Join", "Home")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        @Html.ActionLink("State", "State", "Pages", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Contacts", "Contacts", "State")</li>
                            <li>@Html.ActionLink("Meetings", "Meetings", "State")</li>
                            <li>@Html.ActionLink("Documents and Forms", "Documents", "State")</li>
                            <li>@Html.ActionLink("ByLaws and Policies", "ByLaws", "State")</li>
                            @*<li>@Html.ActionLink("Officer Reports", "OfficerReports", "State")</li>*@
                        </ul>
                    </li>
                    <li class="dropdown">
                        @Html.ActionLink("Chapters", "Chapters", "Pages", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Chapter Information", "ChapterList", "Chapters")</li>
                            @*<li>@Html.ActionLink("Chapter Map", "ChapterMap", "Chapters")</li>*@
                            <li>@Html.ActionLink("Documents and Forms", "Documents", "Chapters")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        @Html.ActionLink("Legislative", "Legislative", "Pages", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })
                        <ul class="dropdown-menu" role="menu">
                            @*<li>@Html.ActionLink("News and Alerts", "News", "Legislative")</li>*@
                            @*<li>@Html.ActionLink("Current Bills", "CurrentBills", "Legislative")</li>*@
                            <li>
                                @*@Html.ActionLink("Representatives", "Representatives", "Legislative")*@
                                <ul class="list-style-none">

                                    @*<li>@Html.ActionLink("State Legislators", "StateLegislators", "Legislative")</li>*@
                                    @* <li>@Html.ActionLink("State Congressmen", "StateCongressmen", "Legislative")</li>*@
                                    @*<li>@Html.ActionLink("US Representatives", "USRepresentatives", "Legislative")</li>*@
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Black Thursday", "BlackThursday", "Legislative")</li>
                            <li>@Html.ActionLink("How To Contact", "HowToContact", "Legislative")</li>
                            <li>@Html.ActionLink("Documents and Forms", "Documents", "Legislative")</li>
                            <li>@Html.ActionLink("News from your LAO", "FromYourLAO", "Legislative")</li>
                            @*<li>
                                @Html.ExternalLink("http://www.usdefender.net/", "US Defenders", new { target = "_blank" })
                                <ul class="list-style-none">
                                    <li>@Html.ActionLink("Defenders News", "DefendersNews", "Legislative")</li>
                                    <li>@Html.ActionLink("CTAs and Alerts", "CTAs", "Legislative")</li>
                                </ul>
                            </li>*@
                        </ul>
                    </li>


                    <li class="dropdown">
                        @Html.ActionLink("Citations", "Citations", "Pages", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })
                        <ul class="dropdown-menu" role="menu">
                            @*<li>@Html.ActionLink("Citations News", "News", "Citations")</li>*@
                            <li>@Html.ActionLink("Legal Letters", "LegalLetters", "Citations")</li>
                            <li>@Html.ActionLink("Documents and Forms", "Documents", "Citations")</li>
                            <li>@Html.ActionLink("Register a Citation", "RegisterCitation", "Citations")</li>

                        </ul>
                    </li>
                    @*<li>
                            @Html.ActionLink("Membership", "Membership", "Pages")

                        </li>*@
                    <li class="dropdown">
                        @Html.ActionLink("News", "News", "Pages", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })
                        <ul class="dropdown-menu" role="menu">
                            @*<li>@Html.ActionLink("ABATE State News", "News", "News")</li>*@
                            <li>@Html.ActionLink("Freedom Newsletter", "FreedomNewsletter", "News")</li>

                            <li>
                                @Html.ExternalLink("http://mrf.org", "Motorcycle Rider's Foundation", new { target = "_blank" })
                                @*@Html.ActionLink("Motorcycle Riders Foundation", "MRFNEws", "Pages", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })*@
                                <ul class="list-style-none">
                                    @*<li>@Html.ActionLink("MRF News", "MRFNews", "News")</li>*@
                                    <li>@Html.ActionLink("Flyers and Forms", "FlyersForms", "News")</li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        @Html.ActionLink("Events", "Events", "Pages", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Event Calendar", "EventCalendar", "Events")</li>
                            @*<li>@Html.ActionLink("Black Thursday", "BlackThursday", "Legislative")</li>*@
                            @*<li>@Html.ActionLink("Freedom Rally", "FreedomRally", "Legislative")</li>*@
                            <li>@Html.ActionLink("Swap Meet", "SwapMeet", "Events")</li>
                            <li>@*@Html.ActionLink("Fall Swap Meet", "swapmeet", "Events")*@</li>
                            <li>@Html.ActionLink("Spring Opener", "SpringOpener", "Events")</li>

                        </ul>
                    </li>
                    @*<li class="dropdown">
                            @Html.ActionLink("Other", "Other", "Pages", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Photo Gallery", "Gallery", "Other")</li>
                                <li>@Html.ActionLink("Down Rider", "DownRider", "Other")</li>
                                <li>@Html.ActionLink("Other Links", "OtherLinks", "Other")</li>
                            </ul>
                        </li>*@
                   
                        <li class="dropdown">
                            @Html.ActionLink("My Account", "Other", "Pages", null, new { @class = "dropdown-toggle", @data_toggle = "dropdown", aria_expanded = "false", role = "button" })
                            <ul class="dropdown-menu" role="menu">
                                @Html.Partial("_LoginPartial")
                            </ul>
                        </li>
                    
                </ul>
                @*@Html.Partial("_LoginPartial")*@


            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <hr />
    </div>
    @Html.Partial("_LoginModal", new ABATE.Washington.Web.Models.LoginViewModel())

    <footer class="footer">
        <div class="text-center">
            <ul class="list-inline">
                <li>© ABATE of Washington. All rights reserved </li>
                <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                <li>@Html.ActionLink("Legal Disclaimer", "LegalDisclaimer", "Home")</li>
                <li>Ride Safe!</li>
                @*<li>Site Map</li>*@

            </ul>
        </div>
    </footer>

</body>
</html>